# Sphinx config for mostlyright Python SDK reference docs.
#
# This build is consumed two ways:
#   1. Locally for preview: `make html` (uses furo theme) — for sanity-checking
#      docstring rendering before pushing a release tag.
#   2. CI for Starlight ingestion: `make markdown` (sphinx-markdown-builder)
#      emits MDX-compatible Markdown into `_build/markdown/`. The
#      `.github/workflows/docs-publish.yml` workflow (Phase 15 W3) copies the
#      `api/` subtree into `mostly-right-landing/src/content/docs/docs/sdk/python/`.
#
# Phase 15 W1 wiring; see `.planning/phases/15-docs-autogen-landing-site/15-PLAN.md`.

from __future__ import annotations

import os
import sys
from pathlib import Path

# Sphinx needs to import every mostlyright.* module that autosummary walks to
# read its docstrings + introspect signatures. The uv workspace exposes the
# three editable packages on sys.path at install time, but the conf.py is
# evaluated by sphinx-build directly (not via `python -m mostlyright`), so we
# explicitly inject the src/ trees of each workspace member. This keeps the
# build working both from a clean `uv sync --group docs` checkout AND from
# CI where the venv layout is identical.
_REPO_ROOT = Path(__file__).resolve().parents[2]
for _pkg in ("core", "weather", "markets"):
    _src = _REPO_ROOT / "packages" / _pkg / "src"
    if _src.is_dir():
        sys.path.insert(0, str(_src))

# -- Project ----------------------------------------------------------------

project = "mostlyright"
author = "Mostly Right"
# Keep the release marker in sync with packages/core/src/mostlyright/__init__.py
# `__version__`. We intentionally hard-code the user-facing "0.1.0" here rather
# than importing __version__ — Sphinx is rendering docs for the public surface
# of an unreleased rc1, and the landing site shows the next-shipping number.
release = "0.1.0"

# -- General Sphinx settings ------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",  # NumPy-style docstrings (matches research.py + co.)
    "sphinx.ext.intersphinx",
    "sphinx_autodoc_typehints",
    "myst_parser",
    "sphinx_markdown_builder",
]

# autosummary drives the per-module page generation under `api/`. Enabled
# so `:toctree: api` in index.rst materializes one .rst (and downstream .md)
# per documented module.
autosummary_generate = True

# Napoleon parses NumPy-style sections (Parameters / Returns / Raises / etc.)
# that the canonical reference modules (research.py, snapshot.py,
# live/_stream.py, discover.py) use.
napoleon_numpy_docstring = True
napoleon_use_param = True

# Move type hints out of the function signature into the description block.
# Keeps signatures readable in the MDX output (no `: dict[str, list[tuple[...]]]`
# crammed into one line).
autodoc_typehints = "description"

# Filter what autodoc emits. We want the public surface only:
#   - members: include public attributes / methods
#   - undoc-members: SKIP — undocumented public attrs surface as gaps that
#     should be either docstring'd or explicitly excluded (Phase 15 design
#     pressure to harden the public docstring surface).
#   - private-members / special-members: SKIP — `_foo`, `__init__`, etc.
#     are not part of the contract.
#   - inherited-members: SKIP — DataFrame inherits from pd.DataFrame; we
#     do not want pandas's full surface mirrored into our docs.
autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "private-members": False,
    "special-members": False,
    "inherited-members": False,
    "show-inheritance": True,
}

# Cross-link to upstream docs where we hand off types. Important for users
# clicking through pd.DataFrame / numpy types in our signatures.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
}

# Allow autosummary's autogenerated stubs to live under `_autosummary/`;
# this is the default, made explicit for clarity.
autosummary_imported_members = False

# Tell autodoc to be permissive about import-time failures in optional/lazy
# submodules. `mostlyright.live` is exposed via module __getattr__ and the
# `mostlyright.markets` / `mostlyright.weather` walk pulls in their own
# package's deps. We do NOT want a docs build failure here to silently mask
# a real docstring gap, so we keep warnings on (sphinx-build will emit them
# and Phase 15 verify Step 7 audits the gap list).
autodoc_mock_imports: list[str] = []

# -- Markdown builder (Starlight ingestion path) ----------------------------

# Stable per-heading + per-signature anchor IDs so cross-links from
# hand-curated MDX (quickstart, concepts) into auto-generated API pages
# survive across rebuilds.
markdown_anchor_sections = True
markdown_anchor_signatures = True

# Where the rendered pages will land on the public landing site. Sphinx
# uses this as the URL base when rewriting internal cross-references in
# the emitted Markdown.
markdown_http_base = "/docs/sdk/python"

# -- HTML (local preview only) ----------------------------------------------

html_theme = "furo"

# -- Suppress noisy build warnings that are NOT actionable ------------------
#
# `mostlyright._internal` is intentionally private (single leading underscore
# in package name) — autosummary tries to import it via the recursive walk
# even though `mostlyright.__all__` excludes it. Mark as suppressed at the
# Sphinx level rather than fighting autosummary recursion.
suppress_warnings = [
    "autosummary.import_cycle",
]
