// @tradewinds/codegen — CLI entry point.
//
// Reads canonical schema artifacts from <repoRoot>/schemas/ and emits typed
// TS interfaces + typed data modules into the consumer packages under
// packages-ts/*/src/{schemas,data}/generated/.
//
// Usage:
//   pnpm --filter @tradewinds/codegen run codegen          # emit files
//   pnpm --filter @tradewinds/codegen run codegen --check  # determinism check
//
// Per TS-W0 Wave 3, ajv-standalone validator emission is DEFERRED to TS-W3
// (TS-VALIDATOR-01) — a placeholder file is emitted in its place.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

// -------------------------------------------------------------------------
// Path resolution
// -------------------------------------------------------------------------

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/** Walk up from `start` until we find a directory containing `marker`. */
function findRepoRoot(start: string, marker = "pnpm-workspace.yaml"): string {
  let cur = resolve(start);
  while (true) {
    if (existsSync(join(cur, marker))) return cur;
    const parent = dirname(cur);
    if (parent === cur) {
      throw new Error(
        `Could not find ${marker} walking up from ${start}. Codegen must be run inside the tradewinds repository.`,
      );
    }
    cur = parent;
  }
}

const REPO_ROOT = findRepoRoot(__dirname);
const SCHEMAS_DIR = join(REPO_ROOT, "schemas");
const PACKAGES_TS = join(REPO_ROOT, "packages-ts");

// -------------------------------------------------------------------------
// Header (3-line "AUTO-GENERATED" banner)
// -------------------------------------------------------------------------

function header(sourceRelPath: string): string {
  return `// AUTO-GENERATED by @tradewinds/codegen from schemas/${sourceRelPath}.\n// DO NOT EDIT — regenerate with: pnpm codegen\n// Last manifest SHA recorded in schemas/EXPORT_MANIFEST.json\n`;
}

// -------------------------------------------------------------------------
// Determinism helpers
// -------------------------------------------------------------------------

/** Stable JSON stringify with sorted keys. */
function stableStringify(value: unknown, indent = 2): string {
  const seen = new WeakSet();
  const sort = (v: unknown): unknown => {
    if (v === null || typeof v !== "object") return v;
    if (seen.has(v as object)) return v;
    seen.add(v as object);
    if (Array.isArray(v)) return v.map(sort);
    const sorted: Record<string, unknown> = {};
    for (const k of Object.keys(v as Record<string, unknown>).sort()) {
      sorted[k] = sort((v as Record<string, unknown>)[k]);
    }
    return sorted;
  };
  return JSON.stringify(sort(value), null, indent);
}

/** Serialize a TS literal value. Strings/numbers/null/arrays/objects only. */
function tsLiteral(value: unknown, indent = 0, indentStep = 2): string {
  const pad = " ".repeat(indent);
  const padNext = " ".repeat(indent + indentStep);
  if (value === null) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((v) => `${padNext}${tsLiteral(v, indent + indentStep, indentStep)}`);
    return `[\n${items.join(",\n")},\n${pad}]`;
  }
  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj).sort();
    if (keys.length === 0) return "{}";
    const parts = keys.map((k) => {
      const safeKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
      return `${padNext}${safeKey}: ${tsLiteral(obj[k], indent + indentStep, indentStep)}`;
    });
    return `{\n${parts.join(",\n")},\n${pad}}`;
  }
  throw new Error(`Unserialisable value: ${String(value)}`);
}

// -------------------------------------------------------------------------
// File I/O helpers (in-memory map for --check mode)
// -------------------------------------------------------------------------

type FileMap = Map<string, string>;

function emit(out: FileMap, absPath: string, contents: string): void {
  // Always normalize to LF + single trailing newline.
  let body = contents.replace(/\r\n/g, "\n");
  if (!body.endsWith("\n")) body += "\n";
  out.set(absPath, body);
}

function writeFiles(files: FileMap): void {
  for (const [path, body] of files) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body, "utf8");
  }
}

// -------------------------------------------------------------------------
// Schema → TS interface (json-schema-to-typescript)
// -------------------------------------------------------------------------

/**
 * Map schema id (e.g. "schema.observation.v1") → TS type name
 * (e.g. "ObservationV1").
 */
function schemaIdToTypeName(schemaId: string): string {
  // Strip "schema." prefix, then split on "." and PascalCase each segment.
  const stripped = schemaId.replace(/^schema\./, "");
  return stripped
    .split(/[._]/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

const SCHEMA_FILES = [
  "schema.observation.v1.json",
  "schema.forecast.iem_mos.v1.json",
  "schema.settlement.cli.v1.json",
  "schema.observation_ledger.v1.json",
  "schema.observation_qc.v1.json",
];

async function emitSchemas(out: FileMap): Promise<void> {
  const generatedDir = join(PACKAGES_TS, "core", "src", "schemas", "generated");
  const typeNames: string[] = [];

  for (const fname of SCHEMA_FILES) {
    const absSchema = join(SCHEMAS_DIR, "json", fname);
    const raw = readFileSync(absSchema, "utf8");
    const schema = JSON.parse(raw) as Record<string, unknown>;
    const schemaId = typeof schema.title === "string" ? schema.title : fname.replace(/\.json$/, "");
    const typeName = schemaIdToTypeName(schemaId);
    typeNames.push(typeName);

    // Force a deterministic title so json-schema-to-typescript names the
    // exported interface consistently across runs.
    const schemaForCompile = { ...schema, title: typeName };

    const compiled = await compile(schemaForCompile, typeName, {
      bannerComment: "",
      style: { singleQuote: false, semi: true },
      additionalProperties: false,
      unreachableDefinitions: false,
    });

    // Pull off any "AUTO-GENERATED by" comments the tool emits; we'll add our own.
    const body = compiled.replace(/^\/\*[\s\S]*?\*\/\s*/g, "").trimEnd();
    const outName = fname.replace(/^schema\./, "").replace(/\.json$/, ".ts");
    const outPath = join(generatedDir, outName);
    const hdr = header(`json/${fname}`);
    emit(out, outPath, `${hdr}\n${body}\n`);
  }

  // Barrel: re-export everything from each schema file.
  const barrelLines: string[] = [header("json/*.json")];
  barrelLines.push("");
  for (const fname of SCHEMA_FILES) {
    const base = fname.replace(/^schema\./, "").replace(/\.json$/, "");
    barrelLines.push(`export * from "./${base}.js";`);
  }
  emit(out, join(generatedDir, "index.ts"), barrelLines.join("\n"));

  // Validators placeholder (deferred to TS-W3 / TS-VALIDATOR-01).
  const validatorsDir = join(PACKAGES_TS, "core", "src", "schemas", "validators");
  const placeholder =
    "// AUTO-GENERATED placeholder by @tradewinds/codegen (TS-W0 Wave 3).\n" +
    "// DO NOT EDIT — regenerate with: pnpm codegen\n" +
    "//\n" +
    "// ajv-standalone validator emission is DEFERRED to TS-W3 (TS-VALIDATOR-01).\n" +
    "// Until then, runtime validation falls back to schema-shape checks performed\n" +
    "// in @tradewinds/core directly. See .planning/REQUIREMENTS.md TS-VALIDATOR-01\n" +
    "// for the ajv-standalone wiring spec.\n" +
    "\n" +
    'export const VALIDATORS_DEFERRED_TO = "TS-W3 / TS-VALIDATOR-01";\n';
  emit(out, join(validatorsDir, "index.ts"), placeholder);
}

// -------------------------------------------------------------------------
// stations.json → typed station registry
// -------------------------------------------------------------------------

interface RawStation {
  code: string | null;
  ghcnh_id: string | null;
  icao: string;
  name: string | null;
  tz: string;
  latitude: number | null;
  longitude: number | null;
  // The JSON also has "country" — we drop it to match the spec's StationInfo shape.
  country?: string;
}

function emitStations(out: FileMap): void {
  const absSrc = join(SCHEMAS_DIR, "stations.json");
  const raw = JSON.parse(readFileSync(absSrc, "utf8")) as { stations: RawStation[] };

  // Stable order: sort by icao (the only always-present unique key) for determinism.
  const sorted = [...raw.stations].sort((a, b) => a.icao.localeCompare(b.icao));

  // Strip to StationInfo shape (drop country).
  const stripped = sorted.map((s) => ({
    code: s.code ?? null,
    ghcnh_id: s.ghcnh_id ?? null,
    icao: s.icao,
    name: s.name ?? null,
    tz: s.tz,
    latitude: s.latitude ?? null,
    longitude: s.longitude ?? null,
  }));

  // Build STATIONS array literal.
  const stationsLit = tsLiteral(stripped);

  // Build code → index map (only entries where code is non-null).
  const codeEntries: [string, number][] = [];
  const icaoEntries: [string, number][] = [];
  stripped.forEach((s, idx) => {
    if (s.code !== null) codeEntries.push([s.code, idx]);
    icaoEntries.push([s.icao, idx]);
  });
  codeEntries.sort((a, b) => a[0].localeCompare(b[0]));
  icaoEntries.sort((a, b) => a[0].localeCompare(b[0]));

  const codeMapEntries = codeEntries
    .map(([k, i]) => `  [${JSON.stringify(k)}, STATIONS[${i}]!],`)
    .join("\n");
  const icaoMapEntries = icaoEntries
    .map(([k, i]) => `  [${JSON.stringify(k)}, STATIONS[${i}]!],`)
    .join("\n");

  const body = `${header("stations.json")}\nexport interface StationInfo {\n  code: string | null;\n  ghcnh_id: string | null;\n  icao: string;\n  name: string | null;\n  tz: string;\n  latitude: number | null;\n  longitude: number | null;\n}\n\nexport const STATIONS: ReadonlyArray<StationInfo> = ${stationsLit} as const;\n\nexport const STATION_BY_CODE: ReadonlyMap<string, StationInfo> = new Map<string, StationInfo>([\n${codeMapEntries}\n]);\n\nexport const STATION_BY_ICAO: ReadonlyMap<string, StationInfo> = new Map<string, StationInfo>([\n${icaoMapEntries}\n]);\n`;

  emit(out, join(PACKAGES_TS, "core", "src", "data", "generated", "stations.ts"), body);
}

// -------------------------------------------------------------------------
// source-priority.json → typed priority module
// -------------------------------------------------------------------------

interface RawSourcePriority {
  observation: Record<string, number>;
  climate: Record<string, number>;
  live_v1: {
    name: string;
    source_priority: Record<string, number>;
    secondary_key: string[];
  };
}

function emitSourcePriority(out: FileMap): void {
  const absSrc = join(SCHEMAS_DIR, "source-priority.json");
  const raw = JSON.parse(readFileSync(absSrc, "utf8")) as RawSourcePriority;

  const obs = tsLiteral(raw.observation);
  const climate = tsLiteral(raw.climate);
  const livePolicy = tsLiteral({
    name: raw.live_v1.name,
    sourcePriority: raw.live_v1.source_priority,
    secondaryKey: raw.live_v1.secondary_key,
  });

  const body = `${header("source-priority.json")}\nexport const OBSERVATION_SOURCE_PRIORITY: Readonly<Record<string, number>> = ${obs} as const;\n\nexport const CLIMATE_REPORT_TYPE_PRIORITY: Readonly<Record<string, number>> = ${climate} as const;\n\nexport const LIVE_V1_POLICY: {\n  name: string;\n  sourcePriority: Readonly<Record<string, number>>;\n  secondaryKey: ReadonlyArray<string>;\n} = ${livePolicy} as const;\n`;

  emit(out, join(PACKAGES_TS, "core", "src", "data", "generated", "source-priority.ts"), body);
}

// -------------------------------------------------------------------------
// qc-alpha-rules.json → typed QC rules
// -------------------------------------------------------------------------

interface RawQcRule {
  rule_id: string;
  bit_position: number;
  description: string;
  field: string;
}

function emitQcRules(out: FileMap): void {
  const absSrc = join(SCHEMAS_DIR, "qc-alpha-rules.json");
  const parsed = JSON.parse(readFileSync(absSrc, "utf8")) as Record<string, unknown>;

  if (parsed.gated === true) {
    const reason = typeof parsed.reason === "string" ? parsed.reason : "";
    const body = `${header("qc-alpha-rules.json")}\nexport const QC_ALPHA_RULES_GATED = true as const;\nexport const QC_ALPHA_RULES_REASON = ${JSON.stringify(reason)};\n`;
    emit(out, join(PACKAGES_TS, "core", "src", "data", "generated", "qc-alpha-rules.ts"), body);
    return;
  }

  const rules = parsed.rules as RawQcRule[];
  // Sort by bit_position for determinism (already typically ordered).
  const sorted = [...rules].sort((a, b) => a.bit_position - b.bit_position);
  const rulesLit = tsLiteral(sorted);
  const mapEntries = sorted
    .map((r, i) => `  [${JSON.stringify(r.rule_id)}, QC_ALPHA_RULES[${i}]!],`)
    .join("\n");

  const body = `${header("qc-alpha-rules.json")}\nexport interface QcAlphaRule {\n  rule_id: string;\n  bit_position: number;\n  description: string;\n  field: string;\n}\n\nexport const QC_ALPHA_RULES: ReadonlyArray<QcAlphaRule> = ${rulesLit} as const;\n\nexport const QC_ALPHA_RULES_BY_ID: ReadonlyMap<string, QcAlphaRule> = new Map<string, QcAlphaRule>([\n${mapEntries}\n]);\n`;

  emit(out, join(PACKAGES_TS, "core", "src", "data", "generated", "qc-alpha-rules.ts"), body);
}

// -------------------------------------------------------------------------
// kalshi-settlement-stations.json → markets module
// -------------------------------------------------------------------------

interface RawKalshi {
  stations: Record<string, { station: string; citation: string }>;
  known_wrong: string[];
}

function emitKalshi(out: FileMap): void {
  const absSrc = join(SCHEMAS_DIR, "kalshi-settlement-stations.json");
  const raw = JSON.parse(readFileSync(absSrc, "utf8")) as RawKalshi;

  // Sort cities + known_wrong for determinism.
  const stationsSorted: Record<string, { station: string; citation: string }> = {};
  for (const k of Object.keys(raw.stations).sort()) {
    const v = raw.stations[k];
    if (!v) continue;
    stationsSorted[k] = {
      station: v.station,
      citation: v.citation,
    };
  }
  const knownWrongSorted = [...raw.known_wrong].sort();

  const stationsLit = tsLiteral(stationsSorted);
  const knownWrongLit = tsLiteral(knownWrongSorted);

  const body = `${header("kalshi-settlement-stations.json")}\nexport interface KalshiStation {\n  station: string;\n  citation: string;\n}\n\nexport const KALSHI_SETTLEMENT_STATIONS: Readonly<Record<string, KalshiStation>> = ${stationsLit} as const;\n\nexport const KNOWN_WRONG_STATIONS: ReadonlySet<string> = new Set<string>(${knownWrongLit});\n`;

  emit(out, join(PACKAGES_TS, "markets", "src", "data", "generated", "kalshi-stations.ts"), body);
}

// -------------------------------------------------------------------------
// polymarket-city-stations.json → markets module
// -------------------------------------------------------------------------

function emitPolymarket(out: FileMap): void {
  const absSrc = join(SCHEMAS_DIR, "polymarket-city-stations.json");
  const raw = JSON.parse(readFileSync(absSrc, "utf8")) as Record<string, unknown>;

  if (raw.gated === true) {
    const reason = typeof raw.reason === "string" ? raw.reason : "";
    const body = `${header("polymarket-city-stations.json")}\nexport const POLYMARKET_CITY_STATIONS_GATED = true as const;\nexport const POLYMARKET_CITY_STATIONS_REASON = ${JSON.stringify(reason)};\n`;
    emit(
      out,
      join(PACKAGES_TS, "markets", "src", "data", "generated", "polymarket-city-stations.ts"),
      body,
    );
    return;
  }

  // Real shape: { cities: { <city>: { default: <ICAO> } } }
  const cities = raw.cities as Record<string, { default: string }>;
  const sorted: Record<string, { default: string }> = {};
  for (const k of Object.keys(cities).sort()) {
    const v = cities[k];
    if (!v) continue;
    sorted[k] = { default: v.default };
  }
  const lit = tsLiteral(sorted);

  const body = `${header("polymarket-city-stations.json")}\nexport interface PolymarketCityStation {\n  default: string;\n}\n\nexport const POLYMARKET_CITY_STATIONS: Readonly<Record<string, PolymarketCityStation>> = ${lit} as const;\n`;

  emit(
    out,
    join(PACKAGES_TS, "markets", "src", "data", "generated", "polymarket-city-stations.ts"),
    body,
  );
}

// -------------------------------------------------------------------------
// Barrels for data/generated/index.ts in core + markets
// -------------------------------------------------------------------------

function emitDataBarrels(out: FileMap): void {
  const coreBarrel = `${header("(barrel)")}\nexport * from \"./stations.js\";\nexport * from \"./source-priority.js\";\nexport * from \"./qc-alpha-rules.js\";\n`;
  emit(out, join(PACKAGES_TS, "core", "src", "data", "generated", "index.ts"), coreBarrel);

  const marketsBarrel = `${header("(barrel)")}\nexport * from \"./kalshi-stations.js\";\nexport * from \"./polymarket-city-stations.js\";\n`;
  emit(out, join(PACKAGES_TS, "markets", "src", "data", "generated", "index.ts"), marketsBarrel);
}

// -------------------------------------------------------------------------
// Orchestration
// -------------------------------------------------------------------------

async function generateAll(): Promise<FileMap> {
  const files: FileMap = new Map();
  await emitSchemas(files);
  emitStations(files);
  emitSourcePriority(files);
  emitQcRules(files);
  emitKalshi(files);
  emitPolymarket(files);
  emitDataBarrels(files);
  return files;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const checkMode = args.includes("--check");

  if (checkMode) {
    const a = await generateAll();
    const b = await generateAll();
    if (a.size !== b.size) {
      console.error(`Non-determinism: run 1 emitted ${a.size} files; run 2 emitted ${b.size}.`);
      process.exit(1);
    }
    for (const [path, body] of a) {
      const other = b.get(path);
      if (other === undefined) {
        console.error(`Non-determinism: ${path} only present in run 1.`);
        process.exit(1);
      }
      if (other !== body) {
        console.error(`Non-determinism: ${path} differs between runs.`);
        process.exit(1);
      }
    }
    console.log(`codegen --check: ${a.size} files byte-equal across two runs. OK.`);
    return;
  }

  const files = await generateAll();
  writeFiles(files);
  console.log(`codegen: wrote ${files.size} generated files under packages-ts/`);
  for (const path of [...files.keys()].sort()) {
    const rel = path.startsWith(REPO_ROOT) ? path.slice(REPO_ROOT.length + 1) : path;
    console.log(`  ${rel}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
