// @mostlyrightmd/codegen — CLI entry point.
//
// Reads canonical schema artifacts from <repoRoot>/schemas/ and emits typed
// TS interfaces + typed data modules into the consumer packages under
// packages-ts/*/src/{schemas,data}/generated/.
//
// Usage:
//   pnpm --filter @mostlyrightmd/codegen run codegen          # emit files
//   pnpm --filter @mostlyrightmd/codegen run codegen --check  # determinism check
//
// Per TS-W0 Wave 3, ajv-standalone validator emission is DEFERRED to TS-W3
// (TS-VALIDATOR-01) — a placeholder file is emitted in its place.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import Ajv from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { compile } from "json-schema-to-typescript";

// -------------------------------------------------------------------------
// Path resolution
// -------------------------------------------------------------------------

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/** Walk up from `start` until we find a directory containing `marker`. */
function findRepoRoot(start: string, marker = "pnpm-workspace.yaml"): string {
  let cur = resolve(start);
  while (true) {
    if (existsSync(join(cur, marker))) return cur;
    const parent = dirname(cur);
    if (parent === cur) {
      throw new Error(
        `Could not find ${marker} walking up from ${start}. Codegen must be run inside the mostlyright repository.`,
      );
    }
    cur = parent;
  }
}

const REPO_ROOT = findRepoRoot(__dirname);
const SCHEMAS_DIR = join(REPO_ROOT, "schemas");
const PACKAGES_TS = join(REPO_ROOT, "packages-ts");

// -------------------------------------------------------------------------
// Header (3-line "AUTO-GENERATED" banner)
// -------------------------------------------------------------------------

function header(sourceRelPath: string): string {
  return `// AUTO-GENERATED by @mostlyrightmd/codegen from schemas/${sourceRelPath}.\n// DO NOT EDIT — regenerate with: pnpm codegen\n// Last manifest SHA recorded in schemas/EXPORT_MANIFEST.json\n`;
}

// -------------------------------------------------------------------------
// Determinism helpers
// -------------------------------------------------------------------------

/** Stable JSON stringify with sorted keys. */
function stableStringify(value: unknown, indent = 2): string {
  const seen = new WeakSet();
  const sort = (v: unknown): unknown => {
    if (v === null || typeof v !== "object") return v;
    if (seen.has(v as object)) return v;
    seen.add(v as object);
    if (Array.isArray(v)) return v.map(sort);
    const sorted: Record<string, unknown> = {};
    for (const k of Object.keys(v as Record<string, unknown>).sort()) {
      sorted[k] = sort((v as Record<string, unknown>)[k]);
    }
    return sorted;
  };
  return JSON.stringify(sort(value), null, indent);
}

/** Serialize a TS literal value. Strings/numbers/null/arrays/objects only. */
function tsLiteral(value: unknown, indent = 0, indentStep = 2): string {
  const pad = " ".repeat(indent);
  const padNext = " ".repeat(indent + indentStep);
  if (value === null) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((v) => `${padNext}${tsLiteral(v, indent + indentStep, indentStep)}`);
    return `[\n${items.join(",\n")},\n${pad}]`;
  }
  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj).sort();
    if (keys.length === 0) return "{}";
    const parts = keys.map((k) => {
      const safeKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
      return `${padNext}${safeKey}: ${tsLiteral(obj[k], indent + indentStep, indentStep)}`;
    });
    return `{\n${parts.join(",\n")},\n${pad}}`;
  }
  throw new Error(`Unserialisable value: ${String(value)}`);
}

// -------------------------------------------------------------------------
// File I/O helpers (in-memory map for --check mode)
// -------------------------------------------------------------------------

type FileMap = Map<string, string>;

function emit(out: FileMap, absPath: string, contents: string): void {
  // Always normalize to LF + single trailing newline.
  let body = contents.replace(/\r\n/g, "\n");
  if (!body.endsWith("\n")) body += "\n";
  out.set(absPath, body);
}

function writeFiles(files: FileMap): void {
  for (const [path, body] of files) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body, "utf8");
  }
}

// -------------------------------------------------------------------------
// Schema → TS interface (json-schema-to-typescript)
// -------------------------------------------------------------------------

/**
 * Map schema id (e.g. "schema.observation.v1") → TS type name
 * (e.g. "ObservationV1").
 */
function schemaIdToTypeName(schemaId: string): string {
  // Strip "schema." prefix, then split on "." and PascalCase each segment.
  const stripped = schemaId.replace(/^schema\./, "");
  return stripped
    .split(/[._]/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

const SCHEMA_FILES = [
  "schema.observation.v1.json",
  "schema.forecast.iem_mos.v1.json",
  "schema.forecast.station.v1.json",
  "schema.settlement.cli.v1.json",
  "schema.observation_ledger.v1.json",
  "schema.observation_qc.v1.json",
];

async function emitSchemas(out: FileMap): Promise<void> {
  const generatedDir = join(PACKAGES_TS, "core", "src", "schemas", "generated");
  const typeNames: string[] = [];

  for (const fname of SCHEMA_FILES) {
    const absSchema = join(SCHEMAS_DIR, "json", fname);
    const raw = readFileSync(absSchema, "utf8");
    const schema = JSON.parse(raw) as Record<string, unknown>;
    const schemaId = typeof schema.title === "string" ? schema.title : fname.replace(/\.json$/, "");
    const typeName = schemaIdToTypeName(schemaId);
    typeNames.push(typeName);

    // Force a deterministic title so json-schema-to-typescript names the
    // exported interface consistently across runs.
    const schemaForCompile = { ...schema, title: typeName };

    const compiled = await compile(schemaForCompile, typeName, {
      bannerComment: "",
      style: { singleQuote: false, semi: true },
      additionalProperties: false,
      unreachableDefinitions: false,
    });

    // Pull off any "AUTO-GENERATED by" comments the tool emits; we'll add our own.
    const body = compiled.replace(/^\/\*[\s\S]*?\*\/\s*/g, "").trimEnd();
    const outName = fname.replace(/^schema\./, "").replace(/\.json$/, ".ts");
    const outPath = join(generatedDir, outName);
    const hdr = header(`json/${fname}`);
    emit(out, outPath, `${hdr}\n${body}\n`);
  }

  // Barrel: re-export everything from each schema file.
  const barrelLines: string[] = [header("json/*.json")];
  barrelLines.push("");
  for (const fname of SCHEMA_FILES) {
    const base = fname.replace(/^schema\./, "").replace(/\.json$/, "");
    barrelLines.push(`export * from "./${base}.js";`);
  }
  emit(out, join(generatedDir, "index.ts"), barrelLines.join("\n"));

  // ajv-standalone validator emission (TS-W3 / TS-VALIDATOR-01).
  // Each Group A schema compiles to a standalone validator function with no
  // runtime ajv dependency — MV3-CSP-safe (no eval, no Function ctor).
  emitValidators(out);
}

function emitValidators(out: FileMap): void {
  const validatorsDir = join(PACKAGES_TS, "core", "src", "schemas", "validators");
  const ajv = new Ajv.default({
    code: { source: true, esm: true, lines: true },
    allErrors: true,
    strict: false,
    // Do NOT addFormats — ajv-formats compiles a `require("ajv-formats/dist/
    // formats")` runtime reference into the standalone output, defeating
    // the MV3-CSP guarantee. Format keywords are silently ignored under
    // strict: false; format-style validation (e.g. ISO date-time) lives in
    // the validateRows wrapper post-pass (see format-map.ts), which walks
    // the schema's `format: "date" | "date-time"` fields and applies regex
    // checks (CSP-safe, no eval / no Function ctor).
  });
  const registered: Array<{ id: string; safeName: string }> = [];
  // Per-schema map of { propertyName: "date" | "date-time" } extracted from
  // top-level `properties` at codegen time. Shipped alongside validators so
  // the validateRows wrapper can run a format post-pass without re-parsing
  // schema JSON at runtime (and without bundling jsonschema/ajv-formats).
  const formatMaps: Array<{ id: string; formats: Record<string, "date" | "date-time"> }> = [];
  for (const fname of SCHEMA_FILES) {
    const absSchema = join(SCHEMAS_DIR, "json", fname);
    if (!existsSync(absSchema)) continue;
    const schema = JSON.parse(readFileSync(absSchema, "utf8")) as Record<string, unknown>;
    const id = typeof schema.title === "string" ? schema.title : fname.replace(/\.json$/, "");
    const safe = id.replace(/[^a-zA-Z0-9_]/g, "_");
    // Compile under the schema's $id (or fallback) so ajv can resolve refs.
    const compileKey = `gen-${safe}`;
    ajv.addSchema(schema, compileKey);
    // ESM mode requires a JS-identifier export name; use `safe` (e.g.
    // `schema_observation_v1`) instead of the dotted schema id. The barrel
    // imports under the safe name AND maps it back to the canonical id.
    const code = standaloneCode.default(ajv, { [safe]: compileKey });
    const jsHeader = header(`json/${fname}`);
    // Strip the AGPL/MIT preamble ajv prepends since we already document
    // generation in our header banner.
    emit(out, join(validatorsDir, `${safe}.js`), `${jsHeader}\n${code}`);
    // .d.ts shim: named export matching the safe name (matches the ESM
    // standalone shape — `export { validate as <safe> }`).
    emit(
      out,
      join(validatorsDir, `${safe}.d.ts`),
      `${jsHeader}\ndeclare const ${safe}: ((data: unknown) => boolean) & { errors?: Array<{ instancePath: string; schemaPath: string; keyword: string; params: Record<string, unknown>; message?: string }> | null };\nexport { ${safe} };\n`,
    );
    registered.push({ id, safeName: safe });

    // Extract date / date-time formats from top-level `properties`. We do
    // NOT recurse into nested objects (no canonical Group A schema uses
    // nested object properties; if Group B introduces them, extend here).
    const props = schema.properties as Record<string, unknown> | undefined;
    const formats: Record<string, "date" | "date-time"> = {};
    if (props !== undefined && typeof props === "object" && props !== null) {
      for (const propName of Object.keys(props).sort()) {
        const spec = props[propName] as Record<string, unknown> | undefined;
        if (spec === undefined || spec === null || typeof spec !== "object") continue;
        const fmt = spec.format;
        if (fmt === "date" || fmt === "date-time") {
          formats[propName] = fmt;
        }
      }
    }
    formatMaps.push({ id, formats });
  }

  // Sort for determinism — must NOT depend on schema iteration order.
  registered.sort((a, b) => a.id.localeCompare(b.id));
  formatMaps.sort((a, b) => a.id.localeCompare(b.id));

  // Emit format-map.ts: { schemaId: { propertyName: "date" | "date-time" } }
  const formatMapLines: string[] = [
    header("(generated)"),
    "",
    '// Per-schema map of { propertyName: "date" | "date-time" } extracted',
    "// from `schemas/json/*.json` `properties[*].format` at codegen time.",
    "// Consumed by validateRows() to run a post-pass format check (CSP-safe",
    "// regex, no jsonschema / ajv-formats runtime dependency).",
    "",
    'export type FormatKind = "date" | "date-time";',
    "",
    "export type SchemaFormatMap = Readonly<Record<string, FormatKind>>;",
    "",
    "const FORMAT_MAPS: Readonly<Record<string, SchemaFormatMap>> = Object.freeze({",
  ];
  for (const m of formatMaps) {
    const entries = Object.keys(m.formats)
      .sort()
      .map((k) => `    ${JSON.stringify(k)}: ${JSON.stringify(m.formats[k])},`)
      .join("\n");
    if (entries.length === 0) {
      formatMapLines.push(`  ${JSON.stringify(m.id)}: Object.freeze({}),`);
    } else {
      formatMapLines.push(`  ${JSON.stringify(m.id)}: Object.freeze({`);
      formatMapLines.push(entries);
      formatMapLines.push("  }),");
    }
  }
  formatMapLines.push("});");
  formatMapLines.push("");
  formatMapLines.push(
    "/** Return the per-property format map for `schemaId`, or null if unknown. */",
  );
  formatMapLines.push("export function getFormatMap(schemaId: string): SchemaFormatMap | null {");
  formatMapLines.push("  return FORMAT_MAPS[schemaId] ?? null;");
  formatMapLines.push("}");
  emit(out, join(validatorsDir, "format-map.ts"), formatMapLines.join("\n"));

  const barrelLines: string[] = [
    header("(generated)"),
    "",
    "// ajv-standalone validators compiled by @mostlyrightmd/codegen at build time.",
    "// No runtime ajv dependency — MV3-CSP-safe (no eval, no Function ctor).",
    "// Group A schemas always compile; Group B schemas (when added) fall through",
    "// to the null-return path in `getValidator`.",
    "",
  ];
  for (const r of registered) {
    barrelLines.push(
      `import { ${r.safeName} as validate_${r.safeName} } from "./${r.safeName}.js";`,
    );
  }
  barrelLines.push("");
  barrelLines.push("export type AjvErrorObject = {");
  barrelLines.push("  readonly instancePath: string;");
  barrelLines.push("  readonly schemaPath: string;");
  barrelLines.push("  readonly keyword: string;");
  barrelLines.push("  readonly params: Record<string, unknown>;");
  barrelLines.push("  readonly message?: string;");
  barrelLines.push("};");
  barrelLines.push("");
  barrelLines.push("export type AjvValidator = ((data: unknown) => boolean) & {");
  barrelLines.push("  errors?: AjvErrorObject[] | null;");
  barrelLines.push("};");
  barrelLines.push("");
  barrelLines.push("const VALIDATORS: Record<string, AjvValidator> = {");
  for (const r of registered) {
    barrelLines.push(
      `  ${JSON.stringify(r.id)}: validate_${r.safeName} as unknown as AjvValidator,`,
    );
  }
  barrelLines.push("};");
  barrelLines.push("");
  barrelLines.push("export function getValidator(schemaId: string): AjvValidator | null {");
  barrelLines.push("  return VALIDATORS[schemaId] ?? null;");
  barrelLines.push("}");
  barrelLines.push("");
  barrelLines.push("export function listValidators(): readonly string[] {");
  barrelLines.push("  return Object.freeze(Object.keys(VALIDATORS));");
  barrelLines.push("}");
  barrelLines.push("");
  barrelLines.push('export { getFormatMap } from "./format-map.js";');
  barrelLines.push('export type { FormatKind, SchemaFormatMap } from "./format-map.js";');
  emit(out, join(validatorsDir, "index.ts"), barrelLines.join("\n"));
}

// -------------------------------------------------------------------------
// stations.json → typed station registry
// -------------------------------------------------------------------------

interface RawStation {
  code: string | null;
  ghcnh_id: string | null;
  icao: string;
  name: string | null;
  tz: string;
  latitude: number | null;
  longitude: number | null;
  country: string | null;
  venues: string[] | null;
}

function emitStations(out: FileMap): void {
  const absSrc = join(SCHEMAS_DIR, "stations.json");
  const raw = JSON.parse(readFileSync(absSrc, "utf8")) as { stations: RawStation[] };

  // Stable order: sort by icao (the only always-present unique key) for determinism.
  const sorted = [...raw.stations].sort((a, b) => a.icao.localeCompare(b.icao));

  // Strip to StationInfo shape — preserve `country` so TS consumers can distinguish
  // US vs intl stations (HIGH 2 from TS-W0 iter-1 review), and `venues` (Phase 22)
  // so consumers can filter by prediction-market venue without a US/intl proxy.
  const stripped = sorted.map((s) => ({
    code: s.code ?? null,
    ghcnh_id: s.ghcnh_id ?? null,
    icao: s.icao,
    name: s.name ?? null,
    tz: s.tz,
    latitude: s.latitude ?? null,
    longitude: s.longitude ?? null,
    country: s.country ?? null,
    venues: s.venues ?? [],
  }));

  // Build STATIONS array literal.
  const stationsLit = tsLiteral(stripped);

  // Build code → index map (only entries where code is non-null).
  const codeEntries: [string, number][] = [];
  const icaoEntries: [string, number][] = [];
  stripped.forEach((s, idx) => {
    if (s.code !== null) codeEntries.push([s.code, idx]);
    icaoEntries.push([s.icao, idx]);
  });
  codeEntries.sort((a, b) => a[0].localeCompare(b[0]));
  icaoEntries.sort((a, b) => a[0].localeCompare(b[0]));

  const codeMapEntries = codeEntries
    .map(([k, i]) => `  [${JSON.stringify(k)}, STATIONS[${i}]!],`)
    .join("\n");
  const icaoMapEntries = icaoEntries
    .map(([k, i]) => `  [${JSON.stringify(k)}, STATIONS[${i}]!],`)
    .join("\n");

  const body = `${header("stations.json")}\nexport interface StationInfo {\n  code: string | null;\n  ghcnh_id: string | null;\n  icao: string;\n  name: string | null;\n  tz: string;\n  latitude: number | null;\n  longitude: number | null;\n  country: string | null;\n  venues: ReadonlyArray<string>;\n}\n\nexport const STATIONS: ReadonlyArray<StationInfo> = ${stationsLit} as const;\n\nexport const STATION_BY_CODE: ReadonlyMap<string, StationInfo> = new Map<string, StationInfo>([\n${codeMapEntries}\n]);\n\nexport const STATION_BY_ICAO: ReadonlyMap<string, StationInfo> = new Map<string, StationInfo>([\n${icaoMapEntries}\n]);\n`;

  emit(out, join(PACKAGES_TS, "core", "src", "data", "generated", "stations.ts"), body);
}

// -------------------------------------------------------------------------
// source-priority.json → typed priority module
// -------------------------------------------------------------------------

interface RawSourcePriority {
  observation: Record<string, number>;
  climate: Record<string, number>;
  live_v1: {
    name: string;
    source_priority: Record<string, number>;
    secondary_key: string[];
  };
}

function emitSourcePriority(out: FileMap): void {
  const absSrc = join(SCHEMAS_DIR, "source-priority.json");
  const raw = JSON.parse(readFileSync(absSrc, "utf8")) as RawSourcePriority;

  const obs = tsLiteral(raw.observation);
  const climate = tsLiteral(raw.climate);
  const livePolicy = tsLiteral({
    name: raw.live_v1.name,
    sourcePriority: raw.live_v1.source_priority,
    secondaryKey: raw.live_v1.secondary_key,
  });

  const body = `${header("source-priority.json")}\nexport const OBSERVATION_SOURCE_PRIORITY: Readonly<Record<string, number>> = ${obs} as const;\n\nexport const CLIMATE_REPORT_TYPE_PRIORITY: Readonly<Record<string, number>> = ${climate} as const;\n\nexport const LIVE_V1_POLICY: {\n  name: string;\n  sourcePriority: Readonly<Record<string, number>>;\n  secondaryKey: ReadonlyArray<string>;\n} = ${livePolicy} as const;\n`;

  emit(out, join(PACKAGES_TS, "core", "src", "data", "generated", "source-priority.ts"), body);
}

// -------------------------------------------------------------------------
// qc-alpha-rules.json → typed QC rules
// -------------------------------------------------------------------------

interface RawQcRule {
  rule_id: string;
  bit_position: number;
  description: string;
  field: string;
}

function emitQcRules(out: FileMap): void {
  const absSrc = join(SCHEMAS_DIR, "qc-alpha-rules.json");
  const parsed = JSON.parse(readFileSync(absSrc, "utf8")) as Record<string, unknown>;

  if (parsed.gated === true) {
    const reason = typeof parsed.reason === "string" ? parsed.reason : "";
    const body = `${header("qc-alpha-rules.json")}\nexport const QC_ALPHA_RULES_GATED = true as const;\nexport const QC_ALPHA_RULES_REASON = ${JSON.stringify(reason)};\n`;
    emit(out, join(PACKAGES_TS, "core", "src", "data", "generated", "qc-alpha-rules.ts"), body);
    return;
  }

  const rules = parsed.rules as RawQcRule[];
  // Sort by bit_position for determinism (already typically ordered).
  const sorted = [...rules].sort((a, b) => a.bit_position - b.bit_position);
  const rulesLit = tsLiteral(sorted);
  const mapEntries = sorted
    .map((r, i) => `  [${JSON.stringify(r.rule_id)}, QC_ALPHA_RULES[${i}]!],`)
    .join("\n");

  const body = `${header("qc-alpha-rules.json")}\nexport interface QcAlphaRule {\n  rule_id: string;\n  bit_position: number;\n  description: string;\n  field: string;\n}\n\nexport const QC_ALPHA_RULES: ReadonlyArray<QcAlphaRule> = ${rulesLit} as const;\n\nexport const QC_ALPHA_RULES_BY_ID: ReadonlyMap<string, QcAlphaRule> = new Map<string, QcAlphaRule>([\n${mapEntries}\n]);\n`;

  emit(out, join(PACKAGES_TS, "core", "src", "data", "generated", "qc-alpha-rules.ts"), body);
}

// -------------------------------------------------------------------------
// kalshi-settlement-stations.json → markets module
// -------------------------------------------------------------------------

interface RawKalshi {
  stations: Record<string, { station: string; citation: string }>;
  known_wrong: string[];
}

function emitKalshi(out: FileMap): void {
  const absSrc = join(SCHEMAS_DIR, "kalshi-settlement-stations.json");
  const raw = JSON.parse(readFileSync(absSrc, "utf8")) as RawKalshi;

  // Sort cities + known_wrong for determinism.
  const stationsSorted: Record<string, { station: string; citation: string }> = {};
  for (const k of Object.keys(raw.stations).sort()) {
    const v = raw.stations[k];
    if (!v) continue;
    stationsSorted[k] = {
      station: v.station,
      citation: v.citation,
    };
  }
  const knownWrongSorted = [...raw.known_wrong].sort();

  const stationsLit = tsLiteral(stationsSorted);
  const knownWrongLit = tsLiteral(knownWrongSorted);

  const body = `${header("kalshi-settlement-stations.json")}\nexport interface KalshiStation {\n  station: string;\n  citation: string;\n}\n\nexport const KALSHI_SETTLEMENT_STATIONS: Readonly<Record<string, KalshiStation>> = ${stationsLit} as const;\n\nexport const KNOWN_WRONG_STATIONS: ReadonlySet<string> = new Set<string>(${knownWrongLit});\n`;

  emit(out, join(PACKAGES_TS, "markets", "src", "data", "generated", "kalshi-stations.ts"), body);
}

// -------------------------------------------------------------------------
// polymarket-city-stations.json → markets module
// -------------------------------------------------------------------------

function emitPolymarket(out: FileMap): void {
  const absSrc = join(SCHEMAS_DIR, "polymarket-city-stations.json");
  const raw = JSON.parse(readFileSync(absSrc, "utf8")) as Record<string, unknown>;

  if (raw.gated === true) {
    const reason = typeof raw.reason === "string" ? raw.reason : "";
    const body = `${header("polymarket-city-stations.json")}\nexport const POLYMARKET_CITY_STATIONS_GATED = true as const;\nexport const POLYMARKET_CITY_STATIONS_REASON = ${JSON.stringify(reason)};\n`;
    emit(
      out,
      join(PACKAGES_TS, "markets", "src", "data", "generated", "polymarket-city-stations.ts"),
      body,
    );
    return;
  }

  // Real shape: { cities: { <city>: { default: <ICAO>, high?: <ICAO>, low?: <ICAO>, ... } } }
  // Measure-specific mappings (e.g. paris-low → LFPB, not the default LFPG) MUST
  // be preserved end-to-end — collapsing to `default` only would silently route
  // settlement to the wrong station. See TS-W0 iter-1 CRITICAL 1.
  const cities = raw.cities as Record<string, Readonly<Record<string, string>>>;
  const sorted: Record<string, Record<string, string>> = {};
  for (const cityKey of Object.keys(cities).sort()) {
    const inner = cities[cityKey];
    if (!inner) continue;
    const innerSorted: Record<string, string> = {};
    for (const measureKey of Object.keys(inner).sort()) {
      const station = inner[measureKey];
      if (typeof station !== "string") continue;
      innerSorted[measureKey] = station;
    }
    sorted[cityKey] = innerSorted;
  }
  const lit = tsLiteral(sorted);

  const body = `${header("polymarket-city-stations.json")}\nexport interface PolymarketCityStation {\n  default: string;\n  high?: string;\n  low?: string;\n  [measure: string]: string | undefined;\n}\n\nexport const POLYMARKET_CITY_STATIONS: Readonly<Record<string, PolymarketCityStation>> = ${lit} as const;\n`;

  emit(
    out,
    join(PACKAGES_TS, "markets", "src", "data", "generated", "polymarket-city-stations.ts"),
    body,
  );
}

// -------------------------------------------------------------------------
// Barrels for data/generated/index.ts in core + markets
// -------------------------------------------------------------------------

function emitDataBarrels(out: FileMap): void {
  const coreBarrel = `${header("(barrel)")}\nexport * from \"./stations.js\";\nexport * from \"./source-priority.js\";\nexport * from \"./qc-alpha-rules.js\";\n`;
  emit(out, join(PACKAGES_TS, "core", "src", "data", "generated", "index.ts"), coreBarrel);

  const marketsBarrel = `${header("(barrel)")}\nexport * from \"./kalshi-stations.js\";\nexport * from \"./polymarket-city-stations.js\";\n`;
  emit(out, join(PACKAGES_TS, "markets", "src", "data", "generated", "index.ts"), marketsBarrel);
}

// -------------------------------------------------------------------------
// Orchestration
// -------------------------------------------------------------------------

async function generateAll(): Promise<FileMap> {
  const files: FileMap = new Map();
  await emitSchemas(files);
  emitStations(files);
  emitSourcePriority(files);
  emitQcRules(files);
  emitKalshi(files);
  emitPolymarket(files);
  emitDataBarrels(files);
  return files;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const checkMode = args.includes("--check");

  if (checkMode) {
    const a = await generateAll();
    const b = await generateAll();
    if (a.size !== b.size) {
      console.error(`Non-determinism: run 1 emitted ${a.size} files; run 2 emitted ${b.size}.`);
      process.exit(1);
    }
    for (const [path, body] of a) {
      const other = b.get(path);
      if (other === undefined) {
        console.error(`Non-determinism: ${path} only present in run 1.`);
        process.exit(1);
      }
      if (other !== body) {
        console.error(`Non-determinism: ${path} differs between runs.`);
        process.exit(1);
      }
    }
    console.log(`codegen --check: ${a.size} files byte-equal across two runs. OK.`);
    return;
  }

  const files = await generateAll();
  writeFiles(files);
  console.log(`codegen: wrote ${files.size} generated files under packages-ts/`);
  for (const path of [...files.keys()].sort()) {
    const rel = path.startsWith(REPO_ROOT) ? path.slice(REPO_ROOT.length + 1) : path;
    console.log(`  ${rel}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
