// @tradewinds/core — placeholder scaffold for TS-W0 Wave 1.
// Real implementation (research, snapshot, mode2, transforms, qc, ...) lands in TS-W1+.

export const version = "0.0.0";

export function helloCore(): string {
  return "hello @tradewinds/core";
}

// Re-export generated types + data (NOT auto-generated; hand-maintained barrel).
// The targets ARE auto-generated by @tradewinds/codegen — see packages-ts/codegen.
export * from "./schemas/generated/index.js";
export * from "./data/generated/index.js";

// TS-W1 Wave 1+5: structured exceptions + snapshot math.
export * from "./exceptions/index.js";
export * from "./snapshot.js";

// TS-W3 Plan 04: temporal-safety primitives (TimePoint, KnowledgeView,
// LeakageDetector, assertNoLeakage). Also available via the subpath
// `@tradewinds/core/temporal` for callers who want tighter tree-shaking.
export * from "./temporal/index.js";

// TS-W3 Plan 07: JSON/CSV/TOON serializers. Also available via the subpath
// `@tradewinds/core/formats`. Parquet + DataFrame omitted (see plan 07).
export * from "./formats/index.js";

// Internal modules — re-export selected helpers only. `internal/convert` and
// `internal/bounds` stay deep imports for fetchers + parsers in later waves.
export { fetchWithRetry } from "./internal/http.js";
export type { FetchWithRetryOptions } from "./internal/http.js";
