// @mostlyrightmd/core — placeholder scaffold for TS-W0 Wave 1.
// Real implementation (research, snapshot, mode2, transforms, qc, ...) lands in TS-W1+.

export const version = "0.0.0";

export function helloCore(): string {
  return "hello @mostlyrightmd/core";
}

// Re-export generated types + data (NOT auto-generated; hand-maintained barrel).
// The targets ARE auto-generated by @mostlyrightmd/codegen — see packages-ts/codegen.
export * from "./schemas/generated/index.js";
export * from "./data/generated/index.js";

// TS-W1 Wave 1+5: structured exceptions + snapshot math.
export * from "./exceptions/index.js";
export * from "./snapshot.js";

// TS-W3 Plan 04 / 05 / 07: temporal primitives, formats, and validator.
//
// These surfaces are intentionally NOT re-exported from the main barrel —
// they ship via dedicated subpath exports to keep `@mostlyrightmd/core`'s
// main bundle under its 25 KB size-limit gate (TS-BUNDLE-01). Iter-4 H8
// dropped the root re-exports after Codex caught the bundle at 25,725 B
// (≈125 B over the gate) because TS-W3 piled temporal + formats + cache +
// validator + new error classes onto the main entry.
//
// Use the subpath imports instead:
//   import { TimePoint, KnowledgeView, assertNoLeakage } from "@mostlyrightmd/core/temporal";
//   import { jsonDumps, csvDumps, toonDumps }            from "@mostlyrightmd/core/formats";
//   import { validateRows }                              from "@mostlyrightmd/core/validator";
//   import type { ValidateOptions, ValidateResult }      from "@mostlyrightmd/core/validator";

// Internal modules — re-export selected helpers only. `internal/convert` and
// `internal/bounds` stay deep imports for fetchers + parsers in later waves.
export { fetchWithRetry } from "./internal/http.js";
export type { FetchWithRetryOptions } from "./internal/http.js";
