"""Phase 12 (rename tradewinds -> mostlyright) TypeScript import rewriter.

Matches scoped + unscoped npm package import strings:
    from "@tradewinds/X"  ->  from "@mostlyright/X"
    from '@tradewinds/X'  ->  from '@mostlyright/X'
    import "@tradewinds/X"  ->  import "@mostlyright/X"
    import '@tradewinds/X'  ->  import '@mostlyright/X'
    from "tradewinds"     ->  from "mostlyright"        (bare unscoped meta)
    from 'tradewinds'     ->  from 'mostlyright'
    import "tradewinds"   ->  import "mostlyright"
    import 'tradewinds'   ->  import 'mostlyright'

SKIPS directories: node_modules/, dist/, .git/, generated/
(generated/ is regenerated by pnpm codegen in W3 Task 2; do not rewrite manually.)

Usage:
    python scripts/_phase12_rename_ts.py
"""

from __future__ import annotations

import re
from pathlib import Path

TS_FROM_RE = re.compile(r'(from\s+["\'])@tradewinds/')
TS_IMPORT_RE = re.compile(r'(import\s+["\'])@tradewinds/')
TS_META_FROM_RE = re.compile(r'(from\s+["\'])tradewinds(["\'])')
TS_META_IMPORT_RE = re.compile(r'(import\s+["\'])tradewinds(["\'])')

EXCLUDE_DIRS = {"node_modules", "dist", ".git", "generated"}


def rewrite_line(line: str) -> str:
    new = TS_FROM_RE.sub(r"\1@mostlyright/", line)
    new = TS_IMPORT_RE.sub(r"\1@mostlyright/", new)
    new = TS_META_FROM_RE.sub(r"\1mostlyright\2", new)
    new = TS_META_IMPORT_RE.sub(r"\1mostlyright\2", new)
    return new


def rewrite_file(path: Path) -> int:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    new_lines = [rewrite_line(line) for line in lines]
    n_changed = sum(1 for old, new in zip(lines, new_lines, strict=True) if old != new)
    if n_changed:
        path.write_text("".join(new_lines), encoding="utf-8")
    return n_changed


def main() -> None:
    root = Path("packages-ts")
    total, files = 0, 0
    for path in root.rglob("*"):
        if path.is_dir():
            continue
        if path.suffix not in {".ts", ".tsx"}:
            continue
        if any(part in EXCLUDE_DIRS for part in path.parts):
            continue
        n = rewrite_file(path)
        if n:
            files += 1
            total += n
            print(f"  {path}: {n} lines")
    print(f"\nTS rewrite: {total} lines across {files} files.")


if __name__ == "__main__":
    main()
