// AUTO-GENERATED by @mostlyrightmd/codegen from schemas/(generated).
// DO NOT EDIT — regenerate with: pnpm codegen
// Last manifest SHA recorded in schemas/EXPORT_MANIFEST.json


// Per-schema map of { propertyName: "date" | "date-time" } extracted
// from `schemas/json/*.json` `properties[*].format` at codegen time.
// Consumed by validateRows() to run a post-pass format check (CSP-safe
// regex, no jsonschema / ajv-formats runtime dependency).

export type FormatKind = "date" | "date-time";

export type SchemaFormatMap = Readonly<Record<string, FormatKind>>;

const FORMAT_MAPS: Readonly<Record<string, SchemaFormatMap>> = Object.freeze({
  "schema.forecast.iem_mos.v1": Object.freeze({
    "issued_at": "date-time",
    "valid_at": "date-time",
  }),
  "schema.observation_ledger.v1": Object.freeze({
    "as_of_time": "date-time",
    "observed_at": "date-time",
  }),
  "schema.observation_qc.v1": Object.freeze({
    "as_of_time": "date-time",
    "observed_at": "date-time",
  }),
  "schema.observation.v1": Object.freeze({
    "event_time": "date-time",
  }),
  "schema.settlement.cli.v1": Object.freeze({
    "event_time": "date-time",
    "observation_date": "date",
    "product_release_time": "date-time",
  }),
});

/** Return the per-property format map for `schemaId`, or null if unknown. */
export function getFormatMap(schemaId: string): SchemaFormatMap | null {
  return FORMAT_MAPS[schemaId] ?? null;
}
