// AUTO-GENERATED by @mostlyrightmd/codegen from schemas/(generated).
// DO NOT EDIT — regenerate with: pnpm codegen
// Last manifest SHA recorded in schemas/EXPORT_MANIFEST.json


// ajv-standalone validators compiled by @mostlyrightmd/codegen at build time.
// No runtime ajv dependency — MV3-CSP-safe (no eval, no Function ctor).
// Group A schemas always compile; Group B schemas (when added) fall through
// to the null-return path in `getValidator`.

import { schema_forecast_iem_mos_v1 as validate_schema_forecast_iem_mos_v1 } from "./schema_forecast_iem_mos_v1.js";
import { schema_observation_ledger_v1 as validate_schema_observation_ledger_v1 } from "./schema_observation_ledger_v1.js";
import { schema_observation_qc_v1 as validate_schema_observation_qc_v1 } from "./schema_observation_qc_v1.js";
import { schema_observation_v1 as validate_schema_observation_v1 } from "./schema_observation_v1.js";
import { schema_settlement_cli_v1 as validate_schema_settlement_cli_v1 } from "./schema_settlement_cli_v1.js";

export type AjvErrorObject = {
  readonly instancePath: string;
  readonly schemaPath: string;
  readonly keyword: string;
  readonly params: Record<string, unknown>;
  readonly message?: string;
};

export type AjvValidator = ((data: unknown) => boolean) & {
  errors?: AjvErrorObject[] | null;
};

const VALIDATORS: Record<string, AjvValidator> = {
  "schema.forecast.iem_mos.v1": validate_schema_forecast_iem_mos_v1 as unknown as AjvValidator,
  "schema.observation_ledger.v1": validate_schema_observation_ledger_v1 as unknown as AjvValidator,
  "schema.observation_qc.v1": validate_schema_observation_qc_v1 as unknown as AjvValidator,
  "schema.observation.v1": validate_schema_observation_v1 as unknown as AjvValidator,
  "schema.settlement.cli.v1": validate_schema_settlement_cli_v1 as unknown as AjvValidator,
};

export function getValidator(schemaId: string): AjvValidator | null {
  return VALIDATORS[schemaId] ?? null;
}

export function listValidators(): readonly string[] {
  return Object.freeze(Object.keys(VALIDATORS));
}

export { getFormatMap } from "./format-map.js";
export type { FormatKind, SchemaFormatMap } from "./format-map.js";
