// AUTO-GENERATED by @tradewinds/codegen from schemas/json/schema.observation_qc.v1.json.
// DO NOT EDIT — regenerate with: pnpm codegen
// Last manifest SHA recorded in schemas/EXPORT_MANIFEST.json

declare const schema_observation_qc_v1: ((data: unknown) => boolean) & { errors?: Array<{ instancePath: string; schemaPath: string; keyword: string; params: Record<string, unknown>; message?: string }> | null };
export { schema_observation_qc_v1 };
