// AUTO-GENERATED by @mostlyright/codegen from schemas/json/schema.forecast.iem_mos.v1.json.
// DO NOT EDIT — regenerate with: pnpm codegen
// Last manifest SHA recorded in schemas/EXPORT_MANIFEST.json

"use strict";
export const schema_forecast_iem_mos_v1 = validate21;
const schema32 = {"$id":"https://mostlyright.dev/schemas/schema.forecast.iem_mos.v1.json","$schema":"https://json-schema.org/draft/2020-12/schema","imperialRenames":{"dew_point_c":"dew_point_F","temp_c":"temp_F","wind_speed_ms":"wind_speed_kt"},"properties":{"dew_point_c":{"description":"units: celsius","type":["null","number"]},"forecast_hour":{"description":"units: hours — (valid_at - issued_at).total_seconds() / 3600","type":"integer"},"issued_at":{"description":"model run time (from source `runtime` field)","format":"date-time","type":"string"},"model":{"description":"e.g. NBE, GFS, LAV, MET","type":"string"},"precip_probability":{"description":"units: probability — bounded [0, 1]","type":["null","number"]},"sky_cover_pct":{"description":"units: percent — bounded [0, 100]","type":["integer","null"]},"station":{"type":"string"},"temp_c":{"description":"units: celsius","type":["null","number"]},"valid_at":{"description":"forecast target time (from source `ftime`)","format":"date-time","type":"string"},"wind_dir_deg":{"description":"units: degrees","type":["integer","null"]},"wind_speed_ms":{"description":"units: m/s","type":["null","number"]}},"required":["forecast_hour","issued_at","model","station","valid_at"],"title":"schema.forecast.iem_mos.v1","type":"object","version":"v1"};

function validate21(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://mostlyright.dev/schemas/schema.forecast.iem_mos.v1.json" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate21.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.forecast_hour === undefined){
const err0 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "forecast_hour"},message:"must have required property '"+"forecast_hour"+"'"};
if(vErrors === null){
vErrors = [err0];
}
else {
vErrors.push(err0);
}
errors++;
}
if(data.issued_at === undefined){
const err1 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "issued_at"},message:"must have required property '"+"issued_at"+"'"};
if(vErrors === null){
vErrors = [err1];
}
else {
vErrors.push(err1);
}
errors++;
}
if(data.model === undefined){
const err2 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "model"},message:"must have required property '"+"model"+"'"};
if(vErrors === null){
vErrors = [err2];
}
else {
vErrors.push(err2);
}
errors++;
}
if(data.station === undefined){
const err3 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "station"},message:"must have required property '"+"station"+"'"};
if(vErrors === null){
vErrors = [err3];
}
else {
vErrors.push(err3);
}
errors++;
}
if(data.valid_at === undefined){
const err4 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "valid_at"},message:"must have required property '"+"valid_at"+"'"};
if(vErrors === null){
vErrors = [err4];
}
else {
vErrors.push(err4);
}
errors++;
}
if(data.dew_point_c !== undefined){
let data0 = data.dew_point_c;
if((data0 !== null) && (!(typeof data0 == "number"))){
const err5 = {instancePath:instancePath+"/dew_point_c",schemaPath:"#/properties/dew_point_c/type",keyword:"type",params:{type: schema32.properties.dew_point_c.type},message:"must be null,number"};
if(vErrors === null){
vErrors = [err5];
}
else {
vErrors.push(err5);
}
errors++;
}
}
if(data.forecast_hour !== undefined){
let data1 = data.forecast_hour;
if(!((typeof data1 == "number") && (!(data1 % 1) && !isNaN(data1)))){
const err6 = {instancePath:instancePath+"/forecast_hour",schemaPath:"#/properties/forecast_hour/type",keyword:"type",params:{type: "integer"},message:"must be integer"};
if(vErrors === null){
vErrors = [err6];
}
else {
vErrors.push(err6);
}
errors++;
}
}
if(data.issued_at !== undefined){
if(!(typeof data.issued_at === "string")){
const err7 = {instancePath:instancePath+"/issued_at",schemaPath:"#/properties/issued_at/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err7];
}
else {
vErrors.push(err7);
}
errors++;
}
}
if(data.model !== undefined){
if(typeof data.model !== "string"){
const err8 = {instancePath:instancePath+"/model",schemaPath:"#/properties/model/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err8];
}
else {
vErrors.push(err8);
}
errors++;
}
}
if(data.precip_probability !== undefined){
let data4 = data.precip_probability;
if((data4 !== null) && (!(typeof data4 == "number"))){
const err9 = {instancePath:instancePath+"/precip_probability",schemaPath:"#/properties/precip_probability/type",keyword:"type",params:{type: schema32.properties.precip_probability.type},message:"must be null,number"};
if(vErrors === null){
vErrors = [err9];
}
else {
vErrors.push(err9);
}
errors++;
}
}
if(data.sky_cover_pct !== undefined){
let data5 = data.sky_cover_pct;
if((!((typeof data5 == "number") && (!(data5 % 1) && !isNaN(data5)))) && (data5 !== null)){
const err10 = {instancePath:instancePath+"/sky_cover_pct",schemaPath:"#/properties/sky_cover_pct/type",keyword:"type",params:{type: schema32.properties.sky_cover_pct.type},message:"must be integer,null"};
if(vErrors === null){
vErrors = [err10];
}
else {
vErrors.push(err10);
}
errors++;
}
}
if(data.station !== undefined){
if(typeof data.station !== "string"){
const err11 = {instancePath:instancePath+"/station",schemaPath:"#/properties/station/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err11];
}
else {
vErrors.push(err11);
}
errors++;
}
}
if(data.temp_c !== undefined){
let data7 = data.temp_c;
if((data7 !== null) && (!(typeof data7 == "number"))){
const err12 = {instancePath:instancePath+"/temp_c",schemaPath:"#/properties/temp_c/type",keyword:"type",params:{type: schema32.properties.temp_c.type},message:"must be null,number"};
if(vErrors === null){
vErrors = [err12];
}
else {
vErrors.push(err12);
}
errors++;
}
}
if(data.valid_at !== undefined){
if(!(typeof data.valid_at === "string")){
const err13 = {instancePath:instancePath+"/valid_at",schemaPath:"#/properties/valid_at/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err13];
}
else {
vErrors.push(err13);
}
errors++;
}
}
if(data.wind_dir_deg !== undefined){
let data9 = data.wind_dir_deg;
if((!((typeof data9 == "number") && (!(data9 % 1) && !isNaN(data9)))) && (data9 !== null)){
const err14 = {instancePath:instancePath+"/wind_dir_deg",schemaPath:"#/properties/wind_dir_deg/type",keyword:"type",params:{type: schema32.properties.wind_dir_deg.type},message:"must be integer,null"};
if(vErrors === null){
vErrors = [err14];
}
else {
vErrors.push(err14);
}
errors++;
}
}
if(data.wind_speed_ms !== undefined){
let data10 = data.wind_speed_ms;
if((data10 !== null) && (!(typeof data10 == "number"))){
const err15 = {instancePath:instancePath+"/wind_speed_ms",schemaPath:"#/properties/wind_speed_ms/type",keyword:"type",params:{type: schema32.properties.wind_speed_ms.type},message:"must be null,number"};
if(vErrors === null){
vErrors = [err15];
}
else {
vErrors.push(err15);
}
errors++;
}
}
}
else {
const err16 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"};
if(vErrors === null){
vErrors = [err16];
}
else {
vErrors.push(err16);
}
errors++;
}
validate21.errors = vErrors;
return errors === 0;
}
validate21.evaluated = {"props":{"dew_point_c":true,"forecast_hour":true,"issued_at":true,"model":true,"precip_probability":true,"sky_cover_pct":true,"station":true,"temp_c":true,"valid_at":true,"wind_dir_deg":true,"wind_speed_ms":true},"dynamicProps":false,"dynamicItems":false};
