// AUTO-GENERATED by @mostlyright/codegen from schemas/json/schema.observation_qc.v1.json.
// DO NOT EDIT — regenerate with: pnpm codegen
// Last manifest SHA recorded in schemas/EXPORT_MANIFEST.json

"use strict";
export const schema_observation_qc_v1 = validate24;
const schema35 = {"$id":"https://mostlyright.dev/schemas/schema.observation_qc.v1.json","$schema":"https://json-schema.org/draft/2020-12/schema","properties":{"as_of_time":{"format":"date-time","type":["null","string"]},"detector_metadata":{"description":"JSON-serialized detector payload; shape per qc_system.","type":["null","string"]},"field":{"description":"Observation column the rule evaluated (e.g. temp_c).","type":"string"},"flag":{"enum":["clean","flagged","suspect"],"type":"string"},"ingestion_id":{"type":["null","string"]},"observation_kind":{"enum":["METAR","SPECI",null],"type":["null","string"]},"observed_at":{"format":"date-time","type":"string"},"parser_name":{"type":["null","string"]},"qc_system":{"type":"string"},"qc_version":{"type":"string"},"rule_id":{"type":"string"},"source":{"enum":["awc","ghcnh","iem","ncei"],"type":"string"},"station_code":{"type":"string"}},"required":["field","flag","observed_at","qc_system","qc_version","rule_id","source","station_code"],"title":"schema.observation_qc.v1","type":"object","version":"v1"};

function validate24(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://mostlyright.dev/schemas/schema.observation_qc.v1.json" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate24.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.field === undefined){
const err0 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "field"},message:"must have required property '"+"field"+"'"};
if(vErrors === null){
vErrors = [err0];
}
else {
vErrors.push(err0);
}
errors++;
}
if(data.flag === undefined){
const err1 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "flag"},message:"must have required property '"+"flag"+"'"};
if(vErrors === null){
vErrors = [err1];
}
else {
vErrors.push(err1);
}
errors++;
}
if(data.observed_at === undefined){
const err2 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "observed_at"},message:"must have required property '"+"observed_at"+"'"};
if(vErrors === null){
vErrors = [err2];
}
else {
vErrors.push(err2);
}
errors++;
}
if(data.qc_system === undefined){
const err3 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "qc_system"},message:"must have required property '"+"qc_system"+"'"};
if(vErrors === null){
vErrors = [err3];
}
else {
vErrors.push(err3);
}
errors++;
}
if(data.qc_version === undefined){
const err4 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "qc_version"},message:"must have required property '"+"qc_version"+"'"};
if(vErrors === null){
vErrors = [err4];
}
else {
vErrors.push(err4);
}
errors++;
}
if(data.rule_id === undefined){
const err5 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "rule_id"},message:"must have required property '"+"rule_id"+"'"};
if(vErrors === null){
vErrors = [err5];
}
else {
vErrors.push(err5);
}
errors++;
}
if(data.source === undefined){
const err6 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "source"},message:"must have required property '"+"source"+"'"};
if(vErrors === null){
vErrors = [err6];
}
else {
vErrors.push(err6);
}
errors++;
}
if(data.station_code === undefined){
const err7 = {instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: "station_code"},message:"must have required property '"+"station_code"+"'"};
if(vErrors === null){
vErrors = [err7];
}
else {
vErrors.push(err7);
}
errors++;
}
if(data.as_of_time !== undefined){
let data0 = data.as_of_time;
if((data0 !== null) && (typeof data0 !== "string")){
const err8 = {instancePath:instancePath+"/as_of_time",schemaPath:"#/properties/as_of_time/type",keyword:"type",params:{type: schema35.properties.as_of_time.type},message:"must be null,string"};
if(vErrors === null){
vErrors = [err8];
}
else {
vErrors.push(err8);
}
errors++;
}
}
if(data.detector_metadata !== undefined){
let data1 = data.detector_metadata;
if((data1 !== null) && (typeof data1 !== "string")){
const err9 = {instancePath:instancePath+"/detector_metadata",schemaPath:"#/properties/detector_metadata/type",keyword:"type",params:{type: schema35.properties.detector_metadata.type},message:"must be null,string"};
if(vErrors === null){
vErrors = [err9];
}
else {
vErrors.push(err9);
}
errors++;
}
}
if(data.field !== undefined){
if(typeof data.field !== "string"){
const err10 = {instancePath:instancePath+"/field",schemaPath:"#/properties/field/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err10];
}
else {
vErrors.push(err10);
}
errors++;
}
}
if(data.flag !== undefined){
let data3 = data.flag;
if(typeof data3 !== "string"){
const err11 = {instancePath:instancePath+"/flag",schemaPath:"#/properties/flag/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err11];
}
else {
vErrors.push(err11);
}
errors++;
}
if(!(((data3 === "clean") || (data3 === "flagged")) || (data3 === "suspect"))){
const err12 = {instancePath:instancePath+"/flag",schemaPath:"#/properties/flag/enum",keyword:"enum",params:{allowedValues: schema35.properties.flag.enum},message:"must be equal to one of the allowed values"};
if(vErrors === null){
vErrors = [err12];
}
else {
vErrors.push(err12);
}
errors++;
}
}
if(data.ingestion_id !== undefined){
let data4 = data.ingestion_id;
if((data4 !== null) && (typeof data4 !== "string")){
const err13 = {instancePath:instancePath+"/ingestion_id",schemaPath:"#/properties/ingestion_id/type",keyword:"type",params:{type: schema35.properties.ingestion_id.type},message:"must be null,string"};
if(vErrors === null){
vErrors = [err13];
}
else {
vErrors.push(err13);
}
errors++;
}
}
if(data.observation_kind !== undefined){
let data5 = data.observation_kind;
if((data5 !== null) && (typeof data5 !== "string")){
const err14 = {instancePath:instancePath+"/observation_kind",schemaPath:"#/properties/observation_kind/type",keyword:"type",params:{type: schema35.properties.observation_kind.type},message:"must be null,string"};
if(vErrors === null){
vErrors = [err14];
}
else {
vErrors.push(err14);
}
errors++;
}
if(!(((data5 === "METAR") || (data5 === "SPECI")) || (data5 === null))){
const err15 = {instancePath:instancePath+"/observation_kind",schemaPath:"#/properties/observation_kind/enum",keyword:"enum",params:{allowedValues: schema35.properties.observation_kind.enum},message:"must be equal to one of the allowed values"};
if(vErrors === null){
vErrors = [err15];
}
else {
vErrors.push(err15);
}
errors++;
}
}
if(data.observed_at !== undefined){
if(!(typeof data.observed_at === "string")){
const err16 = {instancePath:instancePath+"/observed_at",schemaPath:"#/properties/observed_at/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err16];
}
else {
vErrors.push(err16);
}
errors++;
}
}
if(data.parser_name !== undefined){
let data7 = data.parser_name;
if((data7 !== null) && (typeof data7 !== "string")){
const err17 = {instancePath:instancePath+"/parser_name",schemaPath:"#/properties/parser_name/type",keyword:"type",params:{type: schema35.properties.parser_name.type},message:"must be null,string"};
if(vErrors === null){
vErrors = [err17];
}
else {
vErrors.push(err17);
}
errors++;
}
}
if(data.qc_system !== undefined){
if(typeof data.qc_system !== "string"){
const err18 = {instancePath:instancePath+"/qc_system",schemaPath:"#/properties/qc_system/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err18];
}
else {
vErrors.push(err18);
}
errors++;
}
}
if(data.qc_version !== undefined){
if(typeof data.qc_version !== "string"){
const err19 = {instancePath:instancePath+"/qc_version",schemaPath:"#/properties/qc_version/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err19];
}
else {
vErrors.push(err19);
}
errors++;
}
}
if(data.rule_id !== undefined){
if(typeof data.rule_id !== "string"){
const err20 = {instancePath:instancePath+"/rule_id",schemaPath:"#/properties/rule_id/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err20];
}
else {
vErrors.push(err20);
}
errors++;
}
}
if(data.source !== undefined){
let data11 = data.source;
if(typeof data11 !== "string"){
const err21 = {instancePath:instancePath+"/source",schemaPath:"#/properties/source/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err21];
}
else {
vErrors.push(err21);
}
errors++;
}
if(!((((data11 === "awc") || (data11 === "ghcnh")) || (data11 === "iem")) || (data11 === "ncei"))){
const err22 = {instancePath:instancePath+"/source",schemaPath:"#/properties/source/enum",keyword:"enum",params:{allowedValues: schema35.properties.source.enum},message:"must be equal to one of the allowed values"};
if(vErrors === null){
vErrors = [err22];
}
else {
vErrors.push(err22);
}
errors++;
}
}
if(data.station_code !== undefined){
if(typeof data.station_code !== "string"){
const err23 = {instancePath:instancePath+"/station_code",schemaPath:"#/properties/station_code/type",keyword:"type",params:{type: "string"},message:"must be string"};
if(vErrors === null){
vErrors = [err23];
}
else {
vErrors.push(err23);
}
errors++;
}
}
}
else {
const err24 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"};
if(vErrors === null){
vErrors = [err24];
}
else {
vErrors.push(err24);
}
errors++;
}
validate24.errors = vErrors;
return errors === 0;
}
validate24.evaluated = {"props":{"as_of_time":true,"detector_metadata":true,"field":true,"flag":true,"ingestion_id":true,"observation_kind":true,"observed_at":true,"parser_name":true,"qc_system":true,"qc_version":true,"rule_id":true,"source":true,"station_code":true},"dynamicProps":false,"dynamicItems":false};
